customhost = "mydatabase.crgkh1rgvqgc.ap-south-1.rds.amazonaws.com"
customuser = "admin"
custompass = "admin123"
customdb = "mydatabase"
custombucket = "my-project2bucket1"
customregion = "ap-south-1"
